version: '3.8'

services:
  app:
    image: ahmedkhamis10/my_app:1.0
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: 123456789
      DB_DATABASE: postgres
      HASH_SALT_ROUNDS: 10
    depends_on:
      db:
        condition: service_healthy  # Wait for db service to be healthy

  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 123456789
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]  # Health check command
      interval: 2s  # Check every 10 seconds
      retries: 1    # Retry 5 times before giving up

